name: Gatsby Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build and deploy
        run: |
          npm install
          npm run prebuild
      - uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.MYPROFILE }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm build and test
        run: |
          npm install
          npm run build
          npm run test
